apiVersion: v2
name: myapp
description: A static NGINX front‑end and a Node.js/Express back‑end (brakmic/express)
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - nginx
  - express
  - nodejs
  - helm
