replicaCount: 1

frontend:
  enabled: true
  image:
    repository: nginx
    tag: "1.21"
  service:
    type: ClusterIP
    port: 80

backend:
  enabled: true
  image:
    repository: brakmic/express
    tag: "latest"
  port: 3000
  path: "/api"

ingress:
  enabled: true
  className: nginx
  host: myapp.local
  path: "/"
