{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}-backend
  labels:
    {{ include "myapp.labels" . | nindent 4 }}
data:
  index.js: |-
{{ .Files.Get "files/api/index.js" | indent 4 }}
{{- end }}