{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}-frontend
  labels:
    {{ include "myapp.labels" . | nindent 4 }}
data:
  index.html: |-
{{ tpl (.Files.Get "files/html/index.html") . | nindent 4 }}
binaryData:
  favicon.ico: {{ .Files.Get "files/html/favicon.ico" | b64enc | quote }}
{{- end }}