{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-backend
  labels:
    {{ include "myapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "myapp.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "myapp.name" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: PORT
              value: "{{ .Values.backend.port }}"
            - name: BASE_PATH
              value: "{{ .Values.backend.path }}"
            - name: APP_VERSION
              value: "{{ .Chart.AppVersion }}"
          volumeMounts:
            - name: backend-index
              mountPath: /app/index.js
              subPath: index.js
      volumes:
        - name: backend-index
          configMap:
            name: {{ include "myapp.fullname" . }}-backend
            items:
              - key: index.js
                path: index.js
{{- end }}