{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-backend
  labels:
    {{ include "myapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "myapp.name" . }}-backend
  ports:
  - port: {{ .Values.api.port }}
    targetPort: {{ .Values.api.port }}
{{- end }}