{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-backend
  labels:
    {{ include "myapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "myapp.name" . }}-backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
{{- end }}