name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.31.0'

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.17.3'

      - name: Load Kubeconfig
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          mkdir -p "$HOME/.kube"
          echo "$KUBE_CONFIG_DATA" | base64 -d > "$HOME/.kube/config"
          chmod 600 "$HOME/.kube/config"

      - name: Helm lint chart
        run: helm lint chart

      - name: Deploy via Helm
        run: |
          helm upgrade --install myapp chart \
            --namespace demo-app --create-namespace \
            --wait --timeout 5m